### PR TITLE
Add more linting rules to improve readability

### PR DESCRIPTION
**Pull request by allyjweir**
Added a few common linting rules lifted liberally from AirBnB's ESLint config. These help improve readability, and standardise code style throughout the codebase.

The diff is a little messy but viewing each commit individually should make this a little easier to review.

### CODE REVIEW

**Comment by eanakashima** [comment]
@allyjweir thanks! We have some folks out of the office right now, so it may take some time to get this and #47 reviewed, but should be by next week.

**Comment by allyjweir** [comment]
@eanakashima thanks for letting me know. Keen to get these merged soon. Got a few more PRs and improvements lined up for this repo and beeline-nodejs. 😄

**Comment by toshok** [comment]
👍 to everything except https://github.com/honeycombio/libhoney-js/pull/46/commits/e4bf66ef8a6244c45e6880196d32d5d94935de69

**Comment by allyjweir** [comment]
What's the reasoning behind not wanting the `enforce_const` rule?

**Comment by toshok** [comment]
philosophical, really:  I think `const` usage should express developer intent, rather than potentially transient properties of the code itself.  so things that are `const` are things we don't expect/want to change, not just things we happen not to currently change.

**Comment by allyjweir** [comment]
Fair enough. I've removed the commit. Hopefully good to go now.

**Comment by toshok** [comment]
🔥

**Comment by allyjweir** [comment]
:tada:

**Pull request merged**
