### PR TITLE
add a proxy config option

### PR DESCRIPTION
**Pull request by toshok**
`superagent` makes this really simple, as it happens.  the proxy can be either a string (`https://my-proxy:1234/`) or a map of proxy options (which I didn't look into.)

the added test is just a smoke test - we pass if a connection is made to the proxy server at all.

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Can we support picking this up via [`HTTP_PROXY` / `HTTPS_PROXY` environment variables](https://unix.stackexchange.com/questions/212894/whats-the-right-format-for-the-http-proxy-environment-variable-caps-or-no-ca)?. Super weirdly it seems like all of the four `http_proxy`, `https_proxy`, `HTTP_PROXY` and `HTTPS_PROXY` probably need to be checked.

**Comment by toshok** [comment]
libhoney-js can't pull anything from environment variables, since the api for doing some doesn't exist in browsers.

**Comment by nathanleclaire** [comment]
> libhoney-js can't pull anything from environment variables, since the api for doing some doesn't exist in browsers.

There's no workaround possible? (i.e., detect when this environment variable API is available)

The prospect helping us find this issue did have those environment variables set, so if that had worked out of the box, they might not have encountered any issues.

**Comment by toshok** [comment]
right, but I think that's something solvable in the beeline.  The beeline _can_ read environment variables, and is responsible for initializing libhoney.

**Pull request merged**
